### ISSUE TITLE
color syntax inside of strings when viewing .bash, .sh, .fish, etc. files

### ISSUE THREAD

**Issue by ghost** [c-steiner/language-awk#5]
This would be an amazing feature.

**Comment by c-steiner** [comment]
I think this would be a good idea, too. But you should address this request to the [language-shellscript](https://github.com/atom/language-shellscript) package.  

My grammar only scopes pure AWK scripts. If I extend it to several kinds of shell syntax I'll get in conflict with Atoms default grammar for shell script.

Basically Atom supports including grammars from within another one and when I started this language package I did some testing on how to use it for highlighting "nested" awk in shell scripts. Finally I dropped it because I wasn't able to completely understand their string matching and I don't want to mess up their syntax highlighting with my untested code. :wink: 

Maybe some of the contributors to the shell script grammar can do this.

**Comment by ghost** [comment]
:+1:
